server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=10.100.5.167 user=postgres password=123456 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  redis:
    addr: 10.100.1.17:30379
    password:
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
