// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: rpc/test.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据类型
type NihongMsg int32

const (
	NihongMsg_Default                  NihongMsg = 0
	NihongMsg_Success                  NihongMsg = 1
	NihongMsg_Fail                     NihongMsg = 2
	NihongMsg_ParamError               NihongMsg = 3      // 参数错误
	NihongMsg_ItemError                NihongMsg = 4      // 材料不足
	NihongMsg_StateError               NihongMsg = 5      // 状态错误
	NihongMsg_SensitiveError           NihongMsg = 6      // 敏感词校验失败
	NihongMsg_PetNumLimitError         NihongMsg = 10001  // 宠物数量被限制
	NihongMsg_PetNotCostError          NihongMsg = 10002  // 宠物不可消耗
	NihongMsg_PetNotSkillError         NihongMsg = 10003  // 宠物没有技能
	NihongMsg_PetSkillLevelLimitError  NihongMsg = 10004  // 宠物技能等级限制
	NihongMsg_PetSkillReplaceError     NihongMsg = 10005  // 宠物技能不能替换
	NihongMsg_PetNumNotEnoughError     NihongMsg = 100006 // 宠物数量不足
	NihongMsg_PetSkillLevelOverError   NihongMsg = 100008 // 宠物技能等级超过
	NihongMsg_PetSkillNotExistError    NihongMsg = 100009 // 宠物技能不存在
	NihongMsg_PetSkillSuccessRateError NihongMsg = 100010 // 宠物技能成功率错误
	NihongMsg_PetNotAllow              NihongMsg = 100011 // 宠物不允许选择
	NihongMsg_PetPoolNotAllowChoice    NihongMsg = 100012 // 卡池不允许选择
	NihongMsg_PetHatchCountNotEnough   NihongMsg = 100013 // 宠物孵化次数不足
	NihongMsg_PetHatchNotChice         NihongMsg = 100014 // 宠物池未选择宠物
	NihongMsg_Item_Repeat_Buy          NihongMsg = 100015 // 重复购买
	NihongMsg_Item_Not_Exist           NihongMsg = 100016 // 物品不存在
	NihongMsg_Item_Not_Enough          NihongMsg = 100017 // 物品不足
)

// Enum value maps for NihongMsg.
var (
	NihongMsg_name = map[int32]string{
		0:      "Default",
		1:      "Success",
		2:      "Fail",
		3:      "ParamError",
		4:      "ItemError",
		5:      "StateError",
		6:      "SensitiveError",
		10001:  "PetNumLimitError",
		10002:  "PetNotCostError",
		10003:  "PetNotSkillError",
		10004:  "PetSkillLevelLimitError",
		10005:  "PetSkillReplaceError",
		100006: "PetNumNotEnoughError",
		100008: "PetSkillLevelOverError",
		100009: "PetSkillNotExistError",
		100010: "PetSkillSuccessRateError",
		100011: "PetNotAllow",
		100012: "PetPoolNotAllowChoice",
		100013: "PetHatchCountNotEnough",
		100014: "PetHatchNotChice",
		100015: "Item_Repeat_Buy",
		100016: "Item_Not_Exist",
		100017: "Item_Not_Enough",
	}
	NihongMsg_value = map[string]int32{
		"Default":                  0,
		"Success":                  1,
		"Fail":                     2,
		"ParamError":               3,
		"ItemError":                4,
		"StateError":               5,
		"SensitiveError":           6,
		"PetNumLimitError":         10001,
		"PetNotCostError":          10002,
		"PetNotSkillError":         10003,
		"PetSkillLevelLimitError":  10004,
		"PetSkillReplaceError":     10005,
		"PetNumNotEnoughError":     100006,
		"PetSkillLevelOverError":   100008,
		"PetSkillNotExistError":    100009,
		"PetSkillSuccessRateError": 100010,
		"PetNotAllow":              100011,
		"PetPoolNotAllowChoice":    100012,
		"PetHatchCountNotEnough":   100013,
		"PetHatchNotChice":         100014,
		"Item_Repeat_Buy":          100015,
		"Item_Not_Exist":           100016,
		"Item_Not_Enough":          100017,
	}
)

func (x NihongMsg) Enum() *NihongMsg {
	p := new(NihongMsg)
	*p = x
	return p
}

func (x NihongMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NihongMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_test_proto_enumTypes[0].Descriptor()
}

func (NihongMsg) Type() protoreflect.EnumType {
	return &file_rpc_test_proto_enumTypes[0]
}

func (x NihongMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NihongMsg.Descriptor instead.
func (NihongMsg) EnumDescriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{0}
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_rpc_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ParameterMsg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChannelId        string                 `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ExtraContent     []byte                 `protobuf:"bytes,3,opt,name=extraContent,proto3" json:"extraContent,omitempty"`
	AppVersion       string                 `protobuf:"bytes,4,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	ResVersion       string                 `protobuf:"bytes,5,opt,name=resVersion,proto3" json:"resVersion,omitempty"`
	AntiCheatContent string                 `protobuf:"bytes,6,opt,name=antiCheatContent,proto3" json:"antiCheatContent,omitempty"`
	Ip               string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParameterMsg) Reset() {
	*x = ParameterMsg{}
	mi := &file_rpc_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterMsg) ProtoMessage() {}

func (x *ParameterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterMsg.ProtoReflect.Descriptor instead.
func (*ParameterMsg) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{1}
}

func (x *ParameterMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParameterMsg) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ParameterMsg) GetExtraContent() []byte {
	if x != nil {
		return x.ExtraContent
	}
	return nil
}

func (x *ParameterMsg) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ParameterMsg) GetResVersion() string {
	if x != nil {
		return x.ResVersion
	}
	return ""
}

func (x *ParameterMsg) GetAntiCheatContent() string {
	if x != nil {
		return x.AntiCheatContent
	}
	return ""
}

func (x *ParameterMsg) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type EntityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Session        int64                  `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`
	FunName        string                 `protobuf:"bytes,4,opt,name=funName,proto3" json:"funName,omitempty"`
	Content        [][]byte               `protobuf:"bytes,5,rep,name=content,proto3" json:"content,omitempty"`
	CallerTaskTags []string               `protobuf:"bytes,6,rep,name=callerTaskTags,proto3" json:"callerTaskTags,omitempty"` //调用者TaskTags
	EntityAbility  string                 `protobuf:"bytes,7,opt,name=entityAbility,proto3" json:"entityAbility,omitempty"`   // ability类名
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_rpc_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{2}
}

func (x *EntityRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityRequest) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *EntityRequest) GetFunName() string {
	if x != nil {
		return x.FunName
	}
	return ""
}

func (x *EntityRequest) GetContent() [][]byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *EntityRequest) GetCallerTaskTags() []string {
	if x != nil {
		return x.CallerTaskTags
	}
	return nil
}

func (x *EntityRequest) GetEntityAbility() string {
	if x != nil {
		return x.EntityAbility
	}
	return ""
}

type BroadcastEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityRequest *EntityRequest         `protobuf:"bytes,1,opt,name=entityRequest,proto3" json:"entityRequest,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastEntityRequest) Reset() {
	*x = BroadcastEntityRequest{}
	mi := &file_rpc_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEntityRequest) ProtoMessage() {}

func (x *BroadcastEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEntityRequest.ProtoReflect.Descriptor instead.
func (*BroadcastEntityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastEntityRequest) GetEntityRequest() *EntityRequest {
	if x != nil {
		return x.EntityRequest
	}
	return nil
}

func (x *BroadcastEntityRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量entity请求
type BatchEntityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityRequests []*EntityRequest       `protobuf:"bytes,1,rep,name=entityRequests,proto3" json:"entityRequests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchEntityRequest) Reset() {
	*x = BatchEntityRequest{}
	mi := &file_rpc_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEntityRequest) ProtoMessage() {}

func (x *BatchEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEntityRequest.ProtoReflect.Descriptor instead.
func (*BatchEntityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEntityRequest) GetEntityRequests() []*EntityRequest {
	if x != nil {
		return x.EntityRequests
	}
	return nil
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_rpc_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{5}
}

func (x *TestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          float32                `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PingSerial    int32                  `protobuf:"varint,3,opt,name=pingSerial,proto3" json:"pingSerial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_rpc_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{6}
}

func (x *PingRequest) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingRequest) GetPingSerial() int32 {
	if x != nil {
		return x.PingSerial
	}
	return 0
}

// 收发协议
type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginAccount  *AccountInfo           `protobuf:"bytes,1,opt,name=loginAccount,proto3" json:"loginAccount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_rpc_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{7}
}

func (x *UserLoginRequest) GetLoginAccount() *AccountInfo {
	if x != nil {
		return x.LoginAccount
	}
	return nil
}

type AccountInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code review info by hulz: userId不用在协议里面带，
	UserId        string            `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string            `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Token         string            `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenL        string            `protobuf:"bytes,4,opt,name=tokenL,proto3" json:"tokenL,omitempty"`
	ChanelId      int32             `protobuf:"varint,5,opt,name=chanelId,proto3" json:"chanelId,omitempty"`
	SubChanelId   int32             `protobuf:"varint,6,opt,name=subChanelId,proto3" json:"subChanelId,omitempty"`                                                                      //子渠道id
	ExtraInfo     map[string]string `protobuf:"bytes,7,rep,name=extraInfo,proto3" json:"extraInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //扩展信息 key->section value->id 0/null-不是 反支-切片id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_rpc_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{8}
}

func (x *AccountInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccountInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccountInfo) GetTokenL() string {
	if x != nil {
		return x.TokenL
	}
	return ""
}

func (x *AccountInfo) GetChanelId() int32 {
	if x != nil {
		return x.ChanelId
	}
	return 0
}

func (x *AccountInfo) GetSubChanelId() int32 {
	if x != nil {
		return x.SubChanelId
	}
	return 0
}

func (x *AccountInfo) GetExtraInfo() map[string]string {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           NihongMsg              `protobuf:"varint,1,opt,name=msg,proto3,enum=rpc.NihongMsg" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_rpc_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{9}
}

func (x *UserLoginResponse) GetMsg() NihongMsg {
	if x != nil {
		return x.Msg
	}
	return NihongMsg_Default
}

var File_rpc_test_proto protoreflect.FileDescriptor

const file_rpc_test_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/test.proto\x12\x03rpc\"1\n" +
	"\vTestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe4\x01\n" +
	"\fParameterMsg\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tchannelId\x18\x02 \x01(\tR\tchannelId\x12\"\n" +
	"\fextraContent\x18\x03 \x01(\fR\fextraContent\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x04 \x01(\tR\n" +
	"appVersion\x12\x1e\n" +
	"\n" +
	"resVersion\x18\x05 \x01(\tR\n" +
	"resVersion\x12*\n" +
	"\x10antiCheatContent\x18\x06 \x01(\tR\x10antiCheatContent\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\"\xcf\x01\n" +
	"\rEntityRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\asession\x18\x03 \x01(\x03R\asession\x12\x18\n" +
	"\afunName\x18\x04 \x01(\tR\afunName\x12\x18\n" +
	"\acontent\x18\x05 \x03(\fR\acontent\x12&\n" +
	"\x0ecallerTaskTags\x18\x06 \x03(\tR\x0ecallerTaskTags\x12$\n" +
	"\rentityAbility\x18\a \x01(\tR\rentityAbility\"d\n" +
	"\x16BroadcastEntityRequest\x128\n" +
	"\rentityRequest\x18\x01 \x01(\v2\x12.rpc.EntityRequestR\rentityRequest\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"P\n" +
	"\x12BatchEntityRequest\x12:\n" +
	"\x0eentityRequests\x18\x01 \x03(\v2\x12.rpc.EntityRequestR\x0eentityRequests\"B\n" +
	"\fTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x02R\x04time\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"pingSerial\x18\x03 \x01(\x05R\n" +
	"pingSerial\"H\n" +
	"\x10UserLoginRequest\x124\n" +
	"\floginAccount\x18\x01 \x01(\v2\x10.rpc.AccountInfoR\floginAccount\"\xaa\x02\n" +
	"\vAccountInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06tokenL\x18\x04 \x01(\tR\x06tokenL\x12\x1a\n" +
	"\bchanelId\x18\x05 \x01(\x05R\bchanelId\x12 \n" +
	"\vsubChanelId\x18\x06 \x01(\x05R\vsubChanelId\x12=\n" +
	"\textraInfo\x18\a \x03(\v2\x1f.rpc.AccountInfo.ExtraInfoEntryR\textraInfo\x1a<\n" +
	"\x0eExtraInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x11UserLoginResponse\x12 \n" +
	"\x03msg\x18\x01 \x01(\x0e2\x0e.rpc.NihongMsgR\x03msg*\x90\x04\n" +
	"\tNihongMsg\x12\v\n" +
	"\aDefault\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\b\n" +
	"\x04Fail\x10\x02\x12\x0e\n" +
	"\n" +
	"ParamError\x10\x03\x12\r\n" +
	"\tItemError\x10\x04\x12\x0e\n" +
	"\n" +
	"StateError\x10\x05\x12\x12\n" +
	"\x0eSensitiveError\x10\x06\x12\x15\n" +
	"\x10PetNumLimitError\x10\x91N\x12\x14\n" +
	"\x0fPetNotCostError\x10\x92N\x12\x15\n" +
	"\x10PetNotSkillError\x10\x93N\x12\x1c\n" +
	"\x17PetSkillLevelLimitError\x10\x94N\x12\x19\n" +
	"\x14PetSkillReplaceError\x10\x95N\x12\x1a\n" +
	"\x14PetNumNotEnoughError\x10\xa6\x8d\x06\x12\x1c\n" +
	"\x16PetSkillLevelOverError\x10\xa8\x8d\x06\x12\x1b\n" +
	"\x15PetSkillNotExistError\x10\xa9\x8d\x06\x12\x1e\n" +
	"\x18PetSkillSuccessRateError\x10\xaa\x8d\x06\x12\x11\n" +
	"\vPetNotAllow\x10\xab\x8d\x06\x12\x1b\n" +
	"\x15PetPoolNotAllowChoice\x10\xac\x8d\x06\x12\x1c\n" +
	"\x16PetHatchCountNotEnough\x10\xad\x8d\x06\x12\x16\n" +
	"\x10PetHatchNotChice\x10\xae\x8d\x06\x12\x15\n" +
	"\x0fItem_Repeat_Buy\x10\xaf\x8d\x06\x12\x14\n" +
	"\x0eItem_Not_Exist\x10\xb0\x8d\x06\x12\x15\n" +
	"\x0fItem_Not_Enough\x10\xb1\x8d\x062D\n" +
	"\fProtoService\x124\n" +
	"\vProtoMethod\x12\x10.rpc.TestRequest\x1a\x11.rpc.TestResponse\"\x00Bc\n" +
	"\x18io.tpf.service.rpc.protoB\fRpcTestProtoP\x01Z7github.com/go-kratos/kratos/v2/api/proto/kratos/api;rpcb\x06proto3"

var (
	file_rpc_test_proto_rawDescOnce sync.Once
	file_rpc_test_proto_rawDescData []byte
)

func file_rpc_test_proto_rawDescGZIP() []byte {
	file_rpc_test_proto_rawDescOnce.Do(func() {
		file_rpc_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_test_proto_rawDesc), len(file_rpc_test_proto_rawDesc)))
	})
	return file_rpc_test_proto_rawDescData
}

var file_rpc_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_test_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_test_proto_goTypes = []any{
	(NihongMsg)(0),                 // 0: rpc.NihongMsg
	(*TestRequest)(nil),            // 1: rpc.TestRequest
	(*ParameterMsg)(nil),           // 2: rpc.ParameterMsg
	(*EntityRequest)(nil),          // 3: rpc.EntityRequest
	(*BroadcastEntityRequest)(nil), // 4: rpc.BroadcastEntityRequest
	(*BatchEntityRequest)(nil),     // 5: rpc.BatchEntityRequest
	(*TestResponse)(nil),           // 6: rpc.TestResponse
	(*PingRequest)(nil),            // 7: rpc.PingRequest
	(*UserLoginRequest)(nil),       // 8: rpc.UserLoginRequest
	(*AccountInfo)(nil),            // 9: rpc.AccountInfo
	(*UserLoginResponse)(nil),      // 10: rpc.UserLoginResponse
	nil,                            // 11: rpc.AccountInfo.ExtraInfoEntry
}
var file_rpc_test_proto_depIdxs = []int32{
	3,  // 0: rpc.BroadcastEntityRequest.entityRequest:type_name -> rpc.EntityRequest
	3,  // 1: rpc.BatchEntityRequest.entityRequests:type_name -> rpc.EntityRequest
	9,  // 2: rpc.UserLoginRequest.loginAccount:type_name -> rpc.AccountInfo
	11, // 3: rpc.AccountInfo.extraInfo:type_name -> rpc.AccountInfo.ExtraInfoEntry
	0,  // 4: rpc.UserLoginResponse.msg:type_name -> rpc.NihongMsg
	1,  // 5: rpc.ProtoService.ProtoMethod:input_type -> rpc.TestRequest
	6,  // 6: rpc.ProtoService.ProtoMethod:output_type -> rpc.TestResponse
	6,  // [6:7] is the sub-list for method output_type
	5,  // [5:6] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_test_proto_init() }
func file_rpc_test_proto_init() {
	if File_rpc_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_test_proto_rawDesc), len(file_rpc_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_test_proto_goTypes,
		DependencyIndexes: file_rpc_test_proto_depIdxs,
		EnumInfos:         file_rpc_test_proto_enumTypes,
		MessageInfos:      file_rpc_test_proto_msgTypes,
	}.Build()
	File_rpc_test_proto = out.File
	file_rpc_test_proto_goTypes = nil
	file_rpc_test_proto_depIdxs = nil
}
