// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: helloworld/v1/demo2.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type Demo2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo2Request) Reset() {
	*x = Demo2Request{}
	mi := &file_helloworld_v1_demo2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo2Request) ProtoMessage() {}

func (x *Demo2Request) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_demo2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo2Request.ProtoReflect.Descriptor instead.
func (*Demo2Request) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_demo2_proto_rawDescGZIP(), []int{0}
}

func (x *Demo2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type Demo2Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo2Reply) Reset() {
	*x = Demo2Reply{}
	mi := &file_helloworld_v1_demo2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo2Reply) ProtoMessage() {}

func (x *Demo2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_demo2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo2Reply.ProtoReflect.Descriptor instead.
func (*Demo2Reply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_demo2_proto_rawDescGZIP(), []int{1}
}

func (x *Demo2Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing the user's name.
type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_helloworld_v1_demo2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_demo2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_demo2_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// The response message containing the greetings
type HelloRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRep) Reset() {
	*x = HelloRep{}
	mi := &file_helloworld_v1_demo2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRep) ProtoMessage() {}

func (x *HelloRep) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_demo2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRep.ProtoReflect.Descriptor instead.
func (*HelloRep) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_demo2_proto_rawDescGZIP(), []int{3}
}

func (x *HelloRep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_helloworld_v1_demo2_proto protoreflect.FileDescriptor

const file_helloworld_v1_demo2_proto_rawDesc = "" +
	"\n" +
	"\x19helloworld/v1/demo2.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fDemo2Request\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"Demo2Reply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\bHelloReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"8\n" +
	"\bHelloRep\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xc0\x01\n" +
	"\x05Demo2\x12[\n" +
	"\x02Hi\x12\x1f.api.helloworld.v1.Demo2Request\x1a\x1d.api.helloworld.v1.Demo2Reply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/demo2/{name}\x12Z\n" +
	"\x05Hello\x12\x1b.api.helloworld.v1.HelloReq\x1a\x1b.api.helloworld.v1.HelloRep\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/demo2/helloB6\n" +
	"\x11api.helloworld.v1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_demo2_proto_rawDescOnce sync.Once
	file_helloworld_v1_demo2_proto_rawDescData []byte
)

func file_helloworld_v1_demo2_proto_rawDescGZIP() []byte {
	file_helloworld_v1_demo2_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_demo2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_demo2_proto_rawDesc), len(file_helloworld_v1_demo2_proto_rawDesc)))
	})
	return file_helloworld_v1_demo2_proto_rawDescData
}

var file_helloworld_v1_demo2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_v1_demo2_proto_goTypes = []any{
	(*Demo2Request)(nil), // 0: api.helloworld.v1.Demo2Request
	(*Demo2Reply)(nil),   // 1: api.helloworld.v1.Demo2Reply
	(*HelloReq)(nil),     // 2: api.helloworld.v1.HelloReq
	(*HelloRep)(nil),     // 3: api.helloworld.v1.HelloRep
}
var file_helloworld_v1_demo2_proto_depIdxs = []int32{
	0, // 0: api.helloworld.v1.Demo2.Hi:input_type -> api.helloworld.v1.Demo2Request
	2, // 1: api.helloworld.v1.Demo2.Hello:input_type -> api.helloworld.v1.HelloReq
	1, // 2: api.helloworld.v1.Demo2.Hi:output_type -> api.helloworld.v1.Demo2Reply
	3, // 3: api.helloworld.v1.Demo2.Hello:output_type -> api.helloworld.v1.HelloRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_demo2_proto_init() }
func file_helloworld_v1_demo2_proto_init() {
	if File_helloworld_v1_demo2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_demo2_proto_rawDesc), len(file_helloworld_v1_demo2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_demo2_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_demo2_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_demo2_proto_msgTypes,
	}.Build()
	File_helloworld_v1_demo2_proto = out.File
	file_helloworld_v1_demo2_proto_goTypes = nil
	file_helloworld_v1_demo2_proto_depIdxs = nil
}
