// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: helloworld/v1/demo2.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Demo2_Hi_FullMethodName    = "/api.helloworld.v1.Demo2/Hi"
	Demo2_Hello_FullMethodName = "/api.helloworld.v1.Demo2/Hello"
)

// Demo2Client is the client API for Demo2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Demo2Client interface {
	// Sends a greeting
	Hi(ctx context.Context, in *Demo2Request, opts ...grpc.CallOption) (*Demo2Reply, error)
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRep, error)
}

type demo2Client struct {
	cc grpc.ClientConnInterface
}

func NewDemo2Client(cc grpc.ClientConnInterface) Demo2Client {
	return &demo2Client{cc}
}

func (c *demo2Client) Hi(ctx context.Context, in *Demo2Request, opts ...grpc.CallOption) (*Demo2Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Demo2Reply)
	err := c.cc.Invoke(ctx, Demo2_Hi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demo2Client) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloRep)
	err := c.cc.Invoke(ctx, Demo2_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Demo2Server is the server API for Demo2 service.
// All implementations must embed UnimplementedDemo2Server
// for forward compatibility.
type Demo2Server interface {
	// Sends a greeting
	Hi(context.Context, *Demo2Request) (*Demo2Reply, error)
	Hello(context.Context, *HelloReq) (*HelloRep, error)
	mustEmbedUnimplementedDemo2Server()
}

// UnimplementedDemo2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemo2Server struct{}

func (UnimplementedDemo2Server) Hi(context.Context, *Demo2Request) (*Demo2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hi not implemented")
}
func (UnimplementedDemo2Server) Hello(context.Context, *HelloReq) (*HelloRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedDemo2Server) mustEmbedUnimplementedDemo2Server() {}
func (UnimplementedDemo2Server) testEmbeddedByValue()               {}

// UnsafeDemo2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Demo2Server will
// result in compilation errors.
type UnsafeDemo2Server interface {
	mustEmbedUnimplementedDemo2Server()
}

func RegisterDemo2Server(s grpc.ServiceRegistrar, srv Demo2Server) {
	// If the following call pancis, it indicates UnimplementedDemo2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Demo2_ServiceDesc, srv)
}

func _Demo2_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demo2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo2Server).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo2_Hi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo2Server).Hi(ctx, req.(*Demo2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo2_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo2Server).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demo2_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo2Server).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Demo2_ServiceDesc is the grpc.ServiceDesc for Demo2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demo2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.helloworld.v1.Demo2",
	HandlerType: (*Demo2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _Demo2_Hi_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _Demo2_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/demo2.proto",
}
