// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: entity/entity.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityResponse_RespCodeType int32

const (
	EntityResponse_OK     EntityResponse_RespCodeType = 0
	EntityResponse_FAILED EntityResponse_RespCodeType = 1
)

// Enum value maps for EntityResponse_RespCodeType.
var (
	EntityResponse_RespCodeType_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	EntityResponse_RespCodeType_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x EntityResponse_RespCodeType) Enum() *EntityResponse_RespCodeType {
	p := new(EntityResponse_RespCodeType)
	*p = x
	return p
}

func (x EntityResponse_RespCodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityResponse_RespCodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_entity_proto_enumTypes[0].Descriptor()
}

func (EntityResponse_RespCodeType) Type() protoreflect.EnumType {
	return &file_entity_entity_proto_enumTypes[0]
}

func (x EntityResponse_RespCodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityResponse_RespCodeType.Descriptor instead.
func (EntityResponse_RespCodeType) EnumDescriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{1, 0}
}

type PubSubResponse_RespCodeType int32

const (
	PubSubResponse_OK      PubSubResponse_RespCodeType = 0
	PubSubResponse_ERROR   PubSubResponse_RespCodeType = 1
	PubSubResponse_NOT_SUB PubSubResponse_RespCodeType = 2
	PubSubResponse_FAIL    PubSubResponse_RespCodeType = 3
	PubSubResponse_EMPTY   PubSubResponse_RespCodeType = 4
)

// Enum value maps for PubSubResponse_RespCodeType.
var (
	PubSubResponse_RespCodeType_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "NOT_SUB",
		3: "FAIL",
		4: "EMPTY",
	}
	PubSubResponse_RespCodeType_value = map[string]int32{
		"OK":      0,
		"ERROR":   1,
		"NOT_SUB": 2,
		"FAIL":    3,
		"EMPTY":   4,
	}
)

func (x PubSubResponse_RespCodeType) Enum() *PubSubResponse_RespCodeType {
	p := new(PubSubResponse_RespCodeType)
	*p = x
	return p
}

func (x PubSubResponse_RespCodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PubSubResponse_RespCodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_entity_proto_enumTypes[1].Descriptor()
}

func (PubSubResponse_RespCodeType) Type() protoreflect.EnumType {
	return &file_entity_entity_proto_enumTypes[1]
}

func (x PubSubResponse_RespCodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PubSubResponse_RespCodeType.Descriptor instead.
func (PubSubResponse_RespCodeType) EnumDescriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{7, 0}
}

type FixAbilityResponse_RespCodeType int32

const (
	FixAbilityResponse_OK     FixAbilityResponse_RespCodeType = 0
	FixAbilityResponse_FAILED FixAbilityResponse_RespCodeType = 1
)

// Enum value maps for FixAbilityResponse_RespCodeType.
var (
	FixAbilityResponse_RespCodeType_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	FixAbilityResponse_RespCodeType_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x FixAbilityResponse_RespCodeType) Enum() *FixAbilityResponse_RespCodeType {
	p := new(FixAbilityResponse_RespCodeType)
	*p = x
	return p
}

func (x FixAbilityResponse_RespCodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixAbilityResponse_RespCodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_entity_proto_enumTypes[2].Descriptor()
}

func (FixAbilityResponse_RespCodeType) Type() protoreflect.EnumType {
	return &file_entity_entity_proto_enumTypes[2]
}

func (x FixAbilityResponse_RespCodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixAbilityResponse_RespCodeType.Descriptor instead.
func (FixAbilityResponse_RespCodeType) EnumDescriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{11, 0}
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Session       int64                  `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`
	FunName       string                 `protobuf:"bytes,4,opt,name=funName,proto3" json:"funName,omitempty"`
	Content       [][]byte               `protobuf:"bytes,5,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_entity_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntityRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityRequest) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *EntityRequest) GetFunName() string {
	if x != nil {
		return x.FunName
	}
	return ""
}

func (x *EntityRequest) GetContent() [][]byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type EntityResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	RespCode      EntityResponse_RespCodeType `protobuf:"varint,1,opt,name=respCode,proto3,enum=kratos.api.EntityResponse_RespCodeType" json:"respCode,omitempty"`
	Session       int64                       `protobuf:"varint,2,opt,name=session,proto3" json:"session,omitempty"`
	Content       [][]byte                    `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	mi := &file_entity_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{1}
}

func (x *EntityResponse) GetRespCode() EntityResponse_RespCodeType {
	if x != nil {
		return x.RespCode
	}
	return EntityResponse_OK
}

func (x *EntityResponse) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *EntityResponse) GetContent() [][]byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type BroadcastEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityRequest *EntityRequest         `protobuf:"bytes,1,opt,name=entityRequest,proto3" json:"entityRequest,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastEntityRequest) Reset() {
	*x = BroadcastEntityRequest{}
	mi := &file_entity_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEntityRequest) ProtoMessage() {}

func (x *BroadcastEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEntityRequest.ProtoReflect.Descriptor instead.
func (*BroadcastEntityRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastEntityRequest) GetEntityRequest() *EntityRequest {
	if x != nil {
		return x.EntityRequest
	}
	return nil
}

func (x *BroadcastEntityRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量entity请求
type BatchEntityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityRequests []*EntityRequest       `protobuf:"bytes,1,rep,name=entityRequests,proto3" json:"entityRequests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchEntityRequest) Reset() {
	*x = BatchEntityRequest{}
	mi := &file_entity_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEntityRequest) ProtoMessage() {}

func (x *BatchEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEntityRequest.ProtoReflect.Descriptor instead.
func (*BatchEntityRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{3}
}

func (x *BatchEntityRequest) GetEntityRequests() []*EntityRequest {
	if x != nil {
		return x.EntityRequests
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          float32                `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PingSerial    int32                  `protobuf:"varint,3,opt,name=pingSerial,proto3" json:"pingSerial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_entity_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingRequest) GetPingSerial() int32 {
	if x != nil {
		return x.PingSerial
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`         // 订阅的主题列表
	EntityName    string                 `protobuf:"bytes,2,opt,name=entityName,proto3" json:"entityName,omitempty"` // 订阅的实体类型
	EntityId      string                 `protobuf:"bytes,3,opt,name=entityId,proto3" json:"entityId,omitempty"`     // 订阅的实体ID
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`   // 命名空间 若无需跨命名空间 则不填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_entity_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubscribeRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *SubscribeRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SubscribeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PubSubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`         // 订阅的主题列表
	EntityName    string                 `protobuf:"bytes,2,opt,name=entityName,proto3" json:"entityName,omitempty"` // 订阅的实体类型
	EntityId      string                 `protobuf:"bytes,3,opt,name=entityId,proto3" json:"entityId,omitempty"`     // 订阅的实体ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubRequest) Reset() {
	*x = PubSubRequest{}
	mi := &file_entity_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubRequest) ProtoMessage() {}

func (x *PubSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubRequest.ProtoReflect.Descriptor instead.
func (*PubSubRequest) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{6}
}

func (x *PubSubRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *PubSubRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *PubSubRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type PubSubResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	RespCode      PubSubResponse_RespCodeType `protobuf:"varint,1,opt,name=respCode,proto3,enum=kratos.api.PubSubResponse_RespCodeType" json:"respCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubResponse) Reset() {
	*x = PubSubResponse{}
	mi := &file_entity_entity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubResponse) ProtoMessage() {}

func (x *PubSubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubResponse.ProtoReflect.Descriptor instead.
func (*PubSubResponse) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{7}
}

func (x *PubSubResponse) GetRespCode() PubSubResponse_RespCodeType {
	if x != nil {
		return x.RespCode
	}
	return PubSubResponse_OK
}

type PubSubAbilityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubAbilityMessage) Reset() {
	*x = PubSubAbilityMessage{}
	mi := &file_entity_entity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubAbilityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubAbilityMessage) ProtoMessage() {}

func (x *PubSubAbilityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubAbilityMessage.ProtoReflect.Descriptor instead.
func (*PubSubAbilityMessage) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{8}
}

func (x *PubSubAbilityMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessage) Reset() {
	*x = PublishMessage{}
	mi := &file_entity_entity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessage) ProtoMessage() {}

func (x *PublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessage.ProtoReflect.Descriptor instead.
func (*PublishMessage) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{9}
}

func (x *PublishMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FixAbilityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixAbilityMessage) Reset() {
	*x = FixAbilityMessage{}
	mi := &file_entity_entity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixAbilityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixAbilityMessage) ProtoMessage() {}

func (x *FixAbilityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixAbilityMessage.ProtoReflect.Descriptor instead.
func (*FixAbilityMessage) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{10}
}

func (x *FixAbilityMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FixAbilityResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	RespCode      FixAbilityResponse_RespCodeType `protobuf:"varint,1,opt,name=respCode,proto3,enum=kratos.api.FixAbilityResponse_RespCodeType" json:"respCode,omitempty"`
	Content       string                          `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixAbilityResponse) Reset() {
	*x = FixAbilityResponse{}
	mi := &file_entity_entity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixAbilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixAbilityResponse) ProtoMessage() {}

func (x *FixAbilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_entity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixAbilityResponse.ProtoReflect.Descriptor instead.
func (*FixAbilityResponse) Descriptor() ([]byte, []int) {
	return file_entity_entity_proto_rawDescGZIP(), []int{11}
}

func (x *FixAbilityResponse) GetRespCode() FixAbilityResponse_RespCodeType {
	if x != nil {
		return x.RespCode
	}
	return FixAbilityResponse_OK
}

func (x *FixAbilityResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_entity_entity_proto protoreflect.FileDescriptor

const file_entity_entity_proto_rawDesc = "" +
	"\n" +
	"\x13entity/entity.proto\x12\n" +
	"kratos.api\"\x81\x01\n" +
	"\rEntityRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\asession\x18\x03 \x01(\x03R\asession\x12\x18\n" +
	"\afunName\x18\x04 \x01(\tR\afunName\x12\x18\n" +
	"\acontent\x18\x05 \x03(\fR\acontent\"\xad\x01\n" +
	"\x0eEntityResponse\x12C\n" +
	"\brespCode\x18\x01 \x01(\x0e2'.kratos.api.EntityResponse.RespCodeTypeR\brespCode\x12\x18\n" +
	"\asession\x18\x02 \x01(\x03R\asession\x12\x18\n" +
	"\acontent\x18\x03 \x03(\fR\acontent\"\"\n" +
	"\fRespCodeType\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"k\n" +
	"\x16BroadcastEntityRequest\x12?\n" +
	"\rentityRequest\x18\x01 \x01(\v2\x19.kratos.api.EntityRequestR\rentityRequest\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"W\n" +
	"\x12BatchEntityRequest\x12A\n" +
	"\x0eentityRequests\x18\x01 \x03(\v2\x19.kratos.api.EntityRequestR\x0eentityRequests\"_\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x02R\x04time\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"pingSerial\x18\x03 \x01(\x05R\n" +
	"pingSerial\"\x84\x01\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12\x1e\n" +
	"\n" +
	"entityName\x18\x02 \x01(\tR\n" +
	"entityName\x12\x1a\n" +
	"\bentityId\x18\x03 \x01(\tR\bentityId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"c\n" +
	"\rPubSubRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12\x1e\n" +
	"\n" +
	"entityName\x18\x02 \x01(\tR\n" +
	"entityName\x12\x1a\n" +
	"\bentityId\x18\x03 \x01(\tR\bentityId\"\x9a\x01\n" +
	"\x0ePubSubResponse\x12C\n" +
	"\brespCode\x18\x01 \x01(\x0e2'.kratos.api.PubSubResponse.RespCodeTypeR\brespCode\"C\n" +
	"\fRespCodeType\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aNOT_SUB\x10\x02\x12\b\n" +
	"\x04FAIL\x10\x03\x12\t\n" +
	"\x05EMPTY\x10\x04\"0\n" +
	"\x14PubSubAbilityMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"*\n" +
	"\x0ePublishMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"-\n" +
	"\x11FixAbilityMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x9b\x01\n" +
	"\x12FixAbilityResponse\x12G\n" +
	"\brespCode\x18\x01 \x01(\x0e2+.kratos.api.FixAbilityResponse.RespCodeTypeR\brespCode\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\"\n" +
	"\fRespCodeType\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01Bd\n" +
	"\x19com.syyx.tpf.entity.protoB\tEntityMsgP\x01Z:github.com/go-kratos/kratos/v2/api/proto/kratos/api;entityb\x06proto3"

var (
	file_entity_entity_proto_rawDescOnce sync.Once
	file_entity_entity_proto_rawDescData []byte
)

func file_entity_entity_proto_rawDescGZIP() []byte {
	file_entity_entity_proto_rawDescOnce.Do(func() {
		file_entity_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_entity_proto_rawDesc), len(file_entity_entity_proto_rawDesc)))
	})
	return file_entity_entity_proto_rawDescData
}

var file_entity_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_entity_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_entity_entity_proto_goTypes = []any{
	(EntityResponse_RespCodeType)(0),     // 0: kratos.api.EntityResponse.RespCodeType
	(PubSubResponse_RespCodeType)(0),     // 1: kratos.api.PubSubResponse.RespCodeType
	(FixAbilityResponse_RespCodeType)(0), // 2: kratos.api.FixAbilityResponse.RespCodeType
	(*EntityRequest)(nil),                // 3: kratos.api.EntityRequest
	(*EntityResponse)(nil),               // 4: kratos.api.EntityResponse
	(*BroadcastEntityRequest)(nil),       // 5: kratos.api.BroadcastEntityRequest
	(*BatchEntityRequest)(nil),           // 6: kratos.api.BatchEntityRequest
	(*PingRequest)(nil),                  // 7: kratos.api.PingRequest
	(*SubscribeRequest)(nil),             // 8: kratos.api.SubscribeRequest
	(*PubSubRequest)(nil),                // 9: kratos.api.PubSubRequest
	(*PubSubResponse)(nil),               // 10: kratos.api.PubSubResponse
	(*PubSubAbilityMessage)(nil),         // 11: kratos.api.PubSubAbilityMessage
	(*PublishMessage)(nil),               // 12: kratos.api.PublishMessage
	(*FixAbilityMessage)(nil),            // 13: kratos.api.FixAbilityMessage
	(*FixAbilityResponse)(nil),           // 14: kratos.api.FixAbilityResponse
}
var file_entity_entity_proto_depIdxs = []int32{
	0, // 0: kratos.api.EntityResponse.respCode:type_name -> kratos.api.EntityResponse.RespCodeType
	3, // 1: kratos.api.BroadcastEntityRequest.entityRequest:type_name -> kratos.api.EntityRequest
	3, // 2: kratos.api.BatchEntityRequest.entityRequests:type_name -> kratos.api.EntityRequest
	1, // 3: kratos.api.PubSubResponse.respCode:type_name -> kratos.api.PubSubResponse.RespCodeType
	2, // 4: kratos.api.FixAbilityResponse.respCode:type_name -> kratos.api.FixAbilityResponse.RespCodeType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_entity_entity_proto_init() }
func file_entity_entity_proto_init() {
	if File_entity_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_entity_proto_rawDesc), len(file_entity_entity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_entity_proto_goTypes,
		DependencyIndexes: file_entity_entity_proto_depIdxs,
		EnumInfos:         file_entity_entity_proto_enumTypes,
		MessageInfos:      file_entity_entity_proto_msgTypes,
	}.Build()
	File_entity_entity_proto = out.File
	file_entity_entity_proto_goTypes = nil
	file_entity_entity_proto_depIdxs = nil
}
